services:
  backend:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
  frontend:
    build: ./src/main/frontend/dmi-react
    ports:
      - "5173:5173"
  mysql:
    image: 'mysql:9.3'
    environment:
      - 'MYSQL_DATABASE=mdi'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpw" ]
      interval: 10s
      timeout: 5s
      retries: 5