spring.security.user.name=test
spring.security.user.password=test

spring.datasource.url=jdbc:mysql://localhost:3306/mdi
spring.datasource.username=root
spring.datasource.password=

logging.level.com.yiran=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.data.redis.host=localhost
spring.data.redis.port=6379

igdb.client-secret=sa5oecqf06naw0nhro2w9n5q8moggt
igdb.client-id=7cgee1enzd8jie79ufcfe2pgylfnv9

secret-key=IW+UWZI86h0kgbntF3ZbarE7mxne9sgvN7daHIxflq4=
